import BottomNav from "@/components/nav/BottomNav";
import Navbar from "@/components/nav/Navbar";
import StatusBar from "@/components/nav/StatusBar";
import ModalContextProvider from "@/context/ModalContext";
import { createClient } from "@/lib/supabase/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Share_Tech_Mono, VT323 } from "next/font/google";

const vt323 = VT323({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vt",
});

const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  const user = data?.claims;

  return (
    <html
      lang="en"
      className={`${vt323.variable} ${shareTechMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ModalContextProvider>
          <Navbar user={user} />
          {children}
          <div id="modal-root"></div>

          {user && (
            <StatusBar
              username={user.user_metadata?.username ?? "williamson"}
            />
          )}
          {user && <BottomNav />}
        </ModalContextProvider>
      </body>
    </html>
  );
}
